/**
 * 🔥 UNIFIED ROLE TYPE DEFINITIONS
 * Two-tier role system:
 * - Tier 1: Licensing Website Roles (Organizational) - OWNER, ADMIN, MEMBER, ACCOUNTING
 * - Tier 2: App-Specific Roles (Functional) - licensing specialist, editor, producer, writer, etc.
 */
export declare enum LicensingRole {
    OWNER = "OWNER",// Organization owner, full access
    ADMIN = "ADMIN",// Organization admin, management access
    MEMBER = "MEMBER",// Regular organization member
    ACCOUNTING = "ACCOUNTING"
}
export declare enum DashboardRole {
    ADMIN = "ADMIN",
    EXEC = "EXEC",
    MANAGER = "MANAGER",
    POST_COORDINATOR = "POST_COORDINATOR",
    PRODUCER = "PRODUCER",
    ASSOCIATE_PRODUCER = "ASSOCIATE_PRODUCER",
    POST_PRODUCER = "POST_PRODUCER",
    LINE_PRODUCER = "LINE_PRODUCER",
    DIRECTOR = "DIRECTOR",
    EDITOR = "EDITOR",
    ASSISTANT_EDITOR = "ASSISTANT_EDITOR",
    WRITER = "WRITER",
    LICENSING_SPECIALIST = "LICENSING_SPECIALIST",
    MEDIA_MANAGER = "MEDIA_MANAGER",
    PRODUCTION_ASSISTANT = "PRODUCTION_ASSISTANT",
    VIEWER = "VIEWER",
    AUDIO_POST = "AUDIO_POST",
    AUDIO_PRODUCTION = "AUDIO_PRODUCTION",
    AUDIO_MIXER = "AUDIO_MIXER",
    SOUND_ENGINEER = "SOUND_ENGINEER",
    COLORIST = "COLORIST",
    GFX_ARTIST = "GFX_ARTIST",
    CAMERA_OPERATOR = "CAMERA_OPERATOR",
    QC_SPECIALIST = "QC_SPECIALIST",
    DIT = "DIT",
    LOCATION_MANAGER = "LOCATION_MANAGER",
    PRODUCTION_MANAGER = "PRODUCTION_MANAGER",
    POST_SUPERVISOR = "POST_SUPERVISOR",
    POST_PA = "POST_PA",
    GUEST = "GUEST"
}
export declare enum ClipShowProRole {
    PRODUCER = "PRODUCER",
    SUPERVISING_PRODUCER = "SUPERVISING_PRODUCER",
    SERIES_PRODUCER = "SERIES_PRODUCER",
    ASSOCIATE_PRODUCER = "ASSOCIATE_PRODUCER",
    DIRECTOR = "DIRECTOR",
    WRITER = "WRITER",
    EDITOR = "EDITOR",
    ASSISTANT_EDITOR = "ASSISTANT_EDITOR",
    ASSEMBLY_EDITOR = "ASSEMBLY_EDITOR",
    LICENSING_SPECIALIST = "LICENSING_SPECIALIST",
    CLEARANCE_COORDINATOR = "CLEARANCE_COORDINATOR",
    RESEARCHER = "RESEARCHER",
    POST_PRODUCER = "POST_PRODUCER",
    LINE_PRODUCER = "LINE_PRODUCER",
    PRODUCTION_ASSISTANT = "PRODUCTION_ASSISTANT",
    MEDIA_MANAGER = "MEDIA_MANAGER"
}
export declare enum CallSheetRole {
    ADMIN = "ADMIN",
    PRODUCER = "PRODUCER",
    COORDINATOR = "COORDINATOR",
    MEMBER = "MEMBER"
}
export declare enum CuesheetRole {
    PRODUCER = "PRODUCER",
    SUPERVISING_PRODUCER = "SUPERVISING_PRODUCER",
    SERIES_PRODUCER = "SERIES_PRODUCER",
    ASSOCIATE_PRODUCER = "ASSOCIATE_PRODUCER",
    DIRECTOR = "DIRECTOR",
    WRITER = "WRITER",
    EDITOR = "EDITOR",
    ASSISTANT_EDITOR = "ASSISTANT_EDITOR",
    ASSEMBLY_EDITOR = "ASSEMBLY_EDITOR",
    LICENSING_SPECIALIST = "LICENSING_SPECIALIST",
    CLEARANCE_COORDINATOR = "CLEARANCE_COORDINATOR",
    RESEARCHER = "RESEARCHER",
    POST_PRODUCER = "POST_PRODUCER",
    LINE_PRODUCER = "LINE_PRODUCER",
    PRODUCTION_ASSISTANT = "PRODUCTION_ASSISTANT",
    MEDIA_MANAGER = "MEDIA_MANAGER",
    ADMIN = "ADMIN",
    VIEWER = "VIEWER"
}
